import React, { ReactNode, useEffect, useState } from "react";
import Head from "next/head";
import type { Metadata } from "next";
import Footer from "@/components/layout/Footer/Footer";
import Cart from "@/components/minicart/Cart";
import CartDrawer from "@/components/minicart/CartDrawer";
import Providers from "./provider";
import TopBanner from "@/components/layout/Banner/TopBanner";
import TopNavbar from "@/components/layout/Navbar/TopNavbar";
import MovileDrawer from "@/components/layout/Navbar/MovileMenu";

interface LayoutProps {
  title?: string;
  children: ReactNode;
}
export const metadata: Metadata = {
  title: "Mi Tienda",
  description: "Generated by create next app",
};

const Layout: React.FC<LayoutProps> = ({ title, children }) => {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [isDrawerMenuOpen, setIsDrawerMenuOpen] = useState(false);

  const handleCartIconClick = () => {
    setIsDrawerOpen(!isDrawerOpen);
  };
  const handleMenuIconClick = () => {
    console.log(isDrawerMenuOpen)
    setIsDrawerMenuOpen(!isDrawerMenuOpen);
  };
  return (
    <div>
      <Head>
        <title>{title ? `${title} - Mi Tienda` : "Mi Tienda"}</title>
        <meta name="description" content="Descripción de mi tienda" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBanner />
      <Providers>
        <TopNavbar onCartIconClick={handleCartIconClick} onMenuIconClick={handleMenuIconClick} />
        <MovileDrawer isOpen={isDrawerMenuOpen} onMenuIconClick={handleMenuIconClick}>
          Menu Lateral
        </MovileDrawer>
        <CartDrawer isOpen={isDrawerOpen} onCartIconClick={handleCartIconClick}>
          <Cart onClose={handleCartIconClick}/>
        </CartDrawer>
        <main className="pb-10">
            {children}
        </main>
        <Footer />
      </Providers>
    </div>
  );
};

export default Layout;
