import React, { ReactNode, useEffect, useState } from "react";
import Head from "next/head";
import type { Metadata } from "next";
// import styles from "../styles/Layout.module.css"; // Estilos opcionales
import Header from "@/components/ui/Header";
import Footer from "@/components/layout/Footer/Footer";
import Cart from "@/components/minicart/Cart";
import CartDrawer from "@/components/minicart/CartDrawer";
import Providers from "./provider";

interface LayoutProps {
  title?: string;
  children: ReactNode;
}
export const metadata: Metadata = {
  title: "Mi Tienda",
  description: "Generated by create next app",
};

const Layout: React.FC<LayoutProps> = ({ title, children }) => {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);

  const handleCartIconClick = () => {
    setIsDrawerOpen(!isDrawerOpen);
  };
  return (
    <div>
      <Head>
        <title>{title ? `${title} - Mi Tienda` : "Mi Tienda"}</title>
        <meta name="description" content="Descripción de mi tienda" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Providers>
        <Header onCartIconClick={handleCartIconClick} />

        <CartDrawer isOpen={isDrawerOpen} onCartIconClick={handleCartIconClick}>
          <Cart />
        </CartDrawer>
        <main className="pb-10">
          {/* <div className="max-w-frame mx-auto px-4 xl:px-0 py-5"> */}
            {children}
          {/* </div> */}
        </main>
        <Footer />
      </Providers>
    </div>
  );
};

export default Layout;
